#############################################################################
# Makefile for building: harbour-wordquiz
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  harbour-wordquiz.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -spec linux-g++ -o Makefile harbour-wordquiz.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/sailfishapp -I/usr/lib64 -isystem /usr/include/xulrunner-qt5-91.13.1 -isystem /usr/include/nspr4 -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = harbour-wordquiz1.0.0
DISTDIR = /c/Users/fraxl/Documents/qt/harbour-wordquiz/.tmp/harbour-wordquiz1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/share/harbour-wordquiz/lib
LIBS          = $(SUBLIBS) -L/usr/lib64/xulrunner-qt5-devel-91.13.1/lib -lqt5embedwidget -lxpcomglue -lxul -Wl,-rpath,/usr/lib64/xulrunner-qt5-91.13.1 -lplds4 -lplc4 -lnspr4 -ldl -lsailfishapp -pie -rdynamic -lmdeclarativecache5 -lQt5Quick -lQt5Multimedia -lQt5Svg -lQt5Gui -lQt5Qml -lQt5Network -lQt5Xml -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = :

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/harbour-wordquiz.cpp \
		src/filehelpers.cpp \
		src/speechdownloader.cpp \
		src/svgdrawing.cpp \
		src/crosswordq.cpp \
		../Crossword/crossword.cpp qrc_qml.cpp \
		moc_speechdownloader.cpp \
		moc_svgdrawing.cpp \
		moc_crosswordq.cpp
OBJECTS       = harbour-wordquiz.o \
		filehelpers.o \
		speechdownloader.o \
		svgdrawing.o \
		crosswordq.o \
		crossword.o \
		qrc_qml.o \
		moc_speechdownloader.o \
		moc_svgdrawing.o \
		moc_crosswordq.o
DIST          = qml/harbour-wordquiz.qml \
		qml/cover/CoverPage.qml \
		qml/pages/HelpView.qml \
		qml/pages/InputTextQuizSilicaEx.qml \
		qml/pages/QuestionPanel.qml \
		qml/pages/QuestionPanelRect.qml \
		qml/pages/WebPopup.qml \
		qml/pages/WikiView.qml \
		qml/pages/DownLoad.qml \
		qml/pages/FirstPage.qml \
		qml/pages/ButtonQuiz.qml \
		qml/pages/CreateNewQuiz.qml \
		qml/pages/EditQuiz.qml \
		qml/pages/HangMan.qml \
		qml/pages/InputTextQuiz.qml \
		qml/pages/InputTextQuizSilica.qml \
		qml/pages/RectRounded.qml \
		qml/pages/TakeQuiz.qml \
		qml/pages/TextList.qml \
		qml/pages/CrossWord.qml \
		qml/QuizFunctions.js \
		qml/CrossWordFunctions.js \
		harbour-wordquiz.desktop \
		rpm/harbour-wordquiz.changes.in \
		rpm/harbour-wordquiz.changes.run.in \
		rpm/harbour-wordquiz.spec \
		rpm/harbour-wordquiz.yaml \
		/usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		harbour-wordquiz.pro src/speechdownloader.h \
		src/filehelpers.h \
		src/svgdrawing.h \
		src/crosswordq.h src/harbour-wordquiz.cpp \
		src/filehelpers.cpp \
		src/speechdownloader.cpp \
		src/svgdrawing.cpp \
		src/crosswordq.cpp \
		../Crossword/crossword.cpp
QMAKE_TARGET  = harbour-wordquiz
DESTDIR       = 
TARGET        = harbour-wordquiz


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: harbour-wordquiz.pro /usr/share/qt5/mkspecs/linux-g++/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		harbour-wordquiz.pro \
		qml.qrc \
		/usr/lib64/libQt5Quick.prl \
		/usr/lib64/libQt5Multimedia.prl \
		/usr/lib64/libQt5Svg.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Qml.prl \
		/usr/lib64/libQt5Network.prl \
		/usr/lib64/libQt5Xml.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -spec linux-g++ -o Makefile harbour-wordquiz.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/sanitize.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_feedback_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/sailfishapp.prf:
/usr/share/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/qt.prf:
/usr/share/qt5/mkspecs/features/resources.prf:
/usr/share/qt5/mkspecs/features/moc.prf:
/usr/share/qt5/mkspecs/features/unix/opengl.prf:
/usr/share/qt5/mkspecs/features/unix/thread.prf:
/usr/share/qt5/mkspecs/features/file_copies.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
harbour-wordquiz.pro:
qml.qrc:
/usr/lib64/libQt5Quick.prl:
/usr/lib64/libQt5Multimedia.prl:
/usr/lib64/libQt5Svg.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Qml.prl:
/usr/lib64/libQt5Network.prl:
/usr/lib64/libQt5Xml.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -spec linux-g++ -o Makefile harbour-wordquiz.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/speechdownloader.h src/filehelpers.h src/svgdrawing.h src/crosswordq.h $(DISTDIR)/
	$(COPY_FILE) --parents src/harbour-wordquiz.cpp src/filehelpers.cpp src/speechdownloader.cpp src/svgdrawing.cpp src/crosswordq.cpp ../Crossword/crossword.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../glosquiz/ITCKRIST.TTF \
		welcome_en.wav \
		../glosquiz/gubbe.svg \
		../glosquiz/dline.svg \
		../glosquiz/glosquiz/flags/france-flag-button-round-icon-128.png \
		qml/pages/r.png \
		qml/pages/hornbig.png \
		qml/pages/thumb.png \
		qml/pages/WebPopup.qml \
		qml/pages/horn.png \
		qml/pages/rm.png \
		qml/pages/harbour-wordquiz.png \
		qml/pages/left.png \
		../glosquiz/glosquiz/flags/spain-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/sweden-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/japan-flag-3d-round-icon-128.png \
		../glosquiz/glosquiz/flags/italy-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/germany-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/united-kingdom-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/hungary-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/norway-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/poland-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/south-korea-flag-button-round-icon-128.png \
		../glosquiz/glosquiz/flags/russia-flag-button-round-icon-128.png
	/usr/lib64/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_speechdownloader.cpp moc_svgdrawing.cpp moc_crosswordq.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_speechdownloader.cpp moc_svgdrawing.cpp moc_crosswordq.cpp
moc_speechdownloader.cpp: src/speechdownloader.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/fraxl/Documents/qt/harbour-wordquiz -I/usr/include/sailfishapp -I/usr/lib64 -I/usr/include/xulrunner-qt5-91.13.1 -I/usr/include/nspr4 -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/speechdownloader.h -o moc_speechdownloader.cpp

moc_svgdrawing.cpp: src/svgdrawing.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/fraxl/Documents/qt/harbour-wordquiz -I/usr/include/sailfishapp -I/usr/lib64 -I/usr/include/xulrunner-qt5-91.13.1 -I/usr/include/nspr4 -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/svgdrawing.h -o moc_svgdrawing.cpp

moc_crosswordq.cpp: ../Crossword/crossword.h \
		src/crosswordq.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/fraxl/Documents/qt/harbour-wordquiz -I/usr/include/sailfishapp -I/usr/lib64 -I/usr/include/xulrunner-qt5-91.13.1 -I/usr/include/nspr4 -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/10.3.1/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/10.3.1/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/crosswordq.h -o moc_crosswordq.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

harbour-wordquiz.o: src/harbour-wordquiz.cpp src/filehelpers.h \
		src/svgdrawing.h \
		src/speechdownloader.h \
		src/crosswordq.h \
		../Crossword/crossword.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o harbour-wordquiz.o src/harbour-wordquiz.cpp

filehelpers.o: src/filehelpers.cpp src/filehelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filehelpers.o src/filehelpers.cpp

speechdownloader.o: src/speechdownloader.cpp src/speechdownloader.h \
		src/filehelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speechdownloader.o src/speechdownloader.cpp

svgdrawing.o: src/svgdrawing.cpp src/svgdrawing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svgdrawing.o src/svgdrawing.cpp

crosswordq.o: src/crosswordq.cpp src/crosswordq.h \
		../Crossword/crossword.h \
		src/filehelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crosswordq.o src/crosswordq.cpp

crossword.o: ../Crossword/crossword.cpp ../Crossword/crossword.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crossword.o ../Crossword/crossword.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_speechdownloader.o: moc_speechdownloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speechdownloader.o moc_speechdownloader.cpp

moc_svgdrawing.o: moc_svgdrawing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_svgdrawing.o moc_svgdrawing.cpp

moc_crosswordq.o: moc_crosswordq.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_crosswordq.o moc_crosswordq.cpp

####### Install

install_qml: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-wordquiz || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-wordquiz
	-$(INSTALL_DIR) /c/Users/fraxl/Documents/qt/harbour-wordquiz/qml $(INSTALL_ROOT)/usr/share/harbour-wordquiz/

uninstall_qml: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-wordquiz/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-wordquiz/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	-$(INSTALL_FILE) /c/Users/fraxl/Documents/qt/harbour-wordquiz/harbour-wordquiz.desktop $(INSTALL_ROOT)/usr/share/applications/

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/harbour-wordquiz.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_icon86x86: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps
	-$(INSTALL_FILE) /c/Users/fraxl/Documents/qt/harbour-wordquiz/icons/86x86/harbour-wordquiz.png $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/

uninstall_icon86x86: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/harbour-wordquiz.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/ 


install_icon108x108: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps
	-$(INSTALL_FILE) /c/Users/fraxl/Documents/qt/harbour-wordquiz/icons/108x108/harbour-wordquiz.png $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/

uninstall_icon108x108: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/harbour-wordquiz.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/ 


install_icon128x128: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps
	-$(INSTALL_FILE) /c/Users/fraxl/Documents/qt/harbour-wordquiz/icons/128x128/harbour-wordquiz.png $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/

uninstall_icon128x128: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/harbour-wordquiz.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 


install_icon172x172: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps
	-$(INSTALL_FILE) /c/Users/fraxl/Documents/qt/harbour-wordquiz/icons/172x172/harbour-wordquiz.png $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/

uninstall_icon172x172: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/harbour-wordquiz.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/ 


install: install_qml install_target install_desktop install_icon86x86 install_icon108x108 install_icon128x128 install_icon172x172  FORCE

uninstall: uninstall_qml uninstall_target uninstall_desktop uninstall_icon86x86 uninstall_icon108x108 uninstall_icon128x128 uninstall_icon172x172  FORCE

FORCE:

